---

# Settings ( https://huggingface.co/Qwen/Qwen3.6-35B-A3B )
#  - Thinking mode for general tasks: temperature=1.0, top_p=0.95, top_k=20, min_p=0.0, presence_penalty=1.5, repetition_penalty=1.0
#  - Thinking mode for precise coding tasks (e.g. WebDev): temperature=0.6, top_p=0.95, top_k=20, min_p=0.0, presence_penalty=0.0, repetition_penalty=1.0
#  - Instruct (or non-thinking) mode for general tasks: temperature=0.7, top_p=0.8, top_k=20, min_p=0.0, presence_penalty=1.5, repetition_penalty=1.0
#  - Instruct (or non-thinking) mode for reasoning tasks: temperature=1.0, top_p=1.0, top_k=40, min_p=0.0, presence_penalty=2.0, repetition_penalty=1.0
# Resources
#  - GPU: 1 x RTX 6000 Pro
#  - VRAM usage: 50.844Gi

services:
  vllm:
    image: vllm/vllm-openai:v0.20.0
    command: >
      RedHatAI/Qwen3.6-35B-A3B-NVFP4
      --served-model-name Qwen3.6-35B-A3B 
      --tensor-parallel-size 1
      --quantization compressed-tensors
      --speculative-config '{"method":"mtp","num_speculative_tokens":3}'
      --dtype auto
      --max-model-len 262144
      --max-num-seqs 64
      --max-num-batched-tokens 16384
      --gpu-memory-utilization 0.85
      --enable-chunked-prefill
      --no-enable-prefix-caching
      --load-format safetensors
      --trust-remote-code
      --attention-backend flash_attn
      --mm-encoder-tp-mode data
      --mm-processor-cache-type shm
      --enable-auto-tool-choice
      --tool-call-parser qwen3_coder
      --reasoning-parser qwen3
    ports:
      - "8000:8000"
    volumes:
      - $HOME/.cache/huggingface:/root/.cache/huggingface
      - $HOME/.cache/vllm:/root/.cache/vllm
      - $PWD/config/models:/configs
    runtime: nvidia
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              capabilities: [gpu]
              device_ids: ["0"]
    environment:
      - VLLM_MEMORY_PROFILER_ESTIMATE_CUDAGRAPHS=1

