
# OS configuration
# - NCCL stuck issue: add `iommu=pt` to Kernel parameters at `/etc/default/grub`
#
# Models
#
# nvidia/MiniMax-M2.7-NVFP4
# lukealonso/MiniMax-M2.7-NVFP4
#   - VRAM: 92.494 ( startup )

services:

  ## OpenWebUI
  vllm-open-webui-minimax-m2.7:
    image: ghcr.io/open-webui/open-webui:latest
    ports:
      - 3001:8080
    environment:
      - OPENAI_API_BASE_URL=http://vllm-minimax-m2.7:8000/v1
    restart: unless-stopped

  # Minimax M2.7 ( https://github.com/vllm-project/recipes/blob/main/MiniMax/MiniMax-M2.md )
  # Size: 229B - 10B active
  # HF:
  #   - https://huggingface.co/lukealonso/MiniMax-M2.7-NVFP4
  # GPU(s): 2 x RTX 6000 Pro
  # VRAM: 2 x 93Gi
  vllm-minimax-m2.7:
    image: vllm/vllm-openai:v0.20.0-cu130
    pull_policy: always
    ipc: host
    shm_size: 32g
    command: >
      lukealonso/MiniMax-M2.7-NVFP4
      --port 8000
      --served-model-name MiniMax-M2.7
      --trust-remote-code
      --kv-cache-dtype fp8
      --max-model-len 191000
      --enable_expert_parallel
      --tensor-parallel-size 2
      --enable-auto-tool-choice
      --tool-call-parser minimax_m2
      --reasoning-parser minimax_m2_append_think
      --enable-chunked-prefill
      --max-num-seqs 4
      --gpu-memory-utilization 0.9556
      --compilation-config '{"cudagraph_mode":"PIECEWISE","cudagraph_num_of_warmups":1}'
    ports:
      - "8000:8000"
    volumes:
      - $HOME/.cache/huggingface:/root/.cache/huggingface
      - $HOME/.cache/flashinfer:/root/.cache/flashinfer
      - $HOME/github/ai-playground/tools/llm/vllm/source/config:/config
    runtime: nvidia
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              capabilities: [gpu]
              device_ids: ["0","1"]
    environment:
      - CUDA_VISIBLE_DEVICES=0,1
      - SAFETENSORS_FAST_GPU=1
      - VLLM_LOGGING_LEVEL=INFO
      - VLLM_USE_FLASHINFER_MOE_FP4=1
      - VLLM_NVFP4_GEMM_BACKEND=cutlass
      - FLASHINFER_JIT_CACHE=/root/.cache/flashinfer  # persist JIT cache
      - VLLM_MEMORY_PROFILER_ESTIMATE_CUDAGRAPHS=1
      - OMP_NUM_THREADS=8
    restart: unless-stopped

