version: "3.8"

services:
  vllm:
    image: vllm/vllm-openai:nightly
    command: >
      --model nvidia/NVIDIA-Nemotron-3-Super-120B-A12B-NVFP4
      --port 8000
      --served-model-name model
      --tensor-parallel-size 1
      --enable-auto-tool-choice
      --enable-prefix-caching
      --language-model-only
      --tool-call-parser qwen3_coder
      --reasoning-parser qwen3
      --kv-cache-dtype fp8
      --gpu-memory-utilization 0.9
      --async-scheduling
      --trust-remote-code
      --attention-backend TRITON_ATTN
      --enable-chunked-prefill
      --max-num-seqs 512
      --max-model-len 1000000
      --reasoning-parser-plugin /config/plugins/reasoning/super_v3_reasoning_parser.py
      --reasoning-parser super_v3
    ports:
      - "8000:8000"
    volumes:
      - $HOME/.cache/huggingface:/root/.cache/huggingface
      - $PWD/config:/config
    runtime: nvidia
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              capabilities: [gpu]
              device_ids: ["0"]
    environment:
      - VLLM_ALLOW_LONG_MAX_MODEL_LEN=1
