version: "3.8"

services:
  vllm:
    image: vllm/vllm-openai
    command: >
      --model cyankiwi/Qwen3.5-27B-AWQ-4bit
      --host 0.0.0.0
      --port 8000
      --served-model-name model
      --tensor-parallel-size 1
      --enable-auto-tool-choice
      --enable-prefix-caching
      --language-model-only
      --tool-call-parser qwen3_coder
      --reasoning-parser qwen3
      --kv-cache-dtype fp8
      --gpu-memory-utilization 0.75
    ports:
      - "8000:8000"
    volumes:
      - $HOME/.cache/huggingface:/root/.cache/huggingface
      - $PWD/config/models:/configs
    runtime: nvidia
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              capabilities: [gpu]
              device_ids: ["0"]
    environment: []

