---

# Models
# - unsloth/Qwen3.5-122B-A10B-GGUF:IQ4_XS - 4 GPUs
# - unsloth/Qwen3.5-35B-A3B-GGUF:Q4_K_M - 1GPU
# - unsloth/Qwen3.5-35B-A3B-GGUF:Q6_K - 2GPU

services:

  openclaw:
    #image: alpine/openclaw:2026.3.13-1-slim
    image: ghcr.io/openclaw/openclaw:latest
    ports:
      - "18789:18789"
      - "18791:18791"
    restart: unless-stopped
    networks:
      - openclaw

  llm:
    # Image tag: https://github.com/ggml-org/llama.cpp/actions/workflows/docker.yml
    # docker compose exec openclaw openclaw config
    #    Custom Provider > http://llm:8000 > agent
    # docker compose exec openclaw openclaw pairing approve telegram K6ARSZRB
    image: ghcr.io/ggml-org/llama.cpp:server-cuda12-b8148
    runtime: nvidia
    environment:
      - NVIDIA_DRIVER_CAPABILITIES=compute,utility
      - LLAMA_CACHE=/root/.cache/llama.cpp
    ports:
      - "8001:8000"
    volumes:
      - ~/.cache/huggingface/hub:/root/.cache/llama.cpp
      - openclaw:/home/node/.openclaw/workspace
    command: >
      --hf-repo unsloth/Qwen3.5-27B-GGUF:Q4_K_S
      --alias agent
      --host 0.0.0.0
      --port 8000
      -ngl 99
      -c 262144
      -np 1
      --jinja
      --cache-type-k q4_0
      --cache-type-v q4_0
      --flash-attn on
      --temp 0.6
      --top-p 0.95
      --min-p 0.0
      --top-k 20
      --presence-penalty 0.0
      --repeat-penalty 1.0
      --chat-template-kwargs '{"enable_thinking": false}'
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              device_ids: ['0']
              capabilities: [gpu]
    restart: unless-stopped
    networks:
      - openclaw

networks:
  openclaw:
    driver: bridge

volumes:
  openclaw:
