---

# Models
# - unsloth/Qwen3.5-122B-A10B-GGUF:IQ4_XS - 4 GPUs
# - unsloth/Qwen3.5-35B-A3B-GGUF:Q4_K_M - 1GPU
# - unsloth/Qwen3.5-35B-A3B-GGUF:Q6_K - 2GPU

services:

  llamacpp-qwen3.5-27b:
    # Image tag: https://github.com/ggml-org/llama.cpp/actions/workflows/docker.yml
    image: ghcr.io/ggml-org/llama.cpp:server-cuda12-b8148
    runtime: nvidia
    environment:
      - NVIDIA_DRIVER_CAPABILITIES=compute,utility
      - LLAMA_CACHE=/root/.cache/llama.cpp
    ports:
      - "8001:8000"
    volumes:
      - ~/.cache/huggingface/hub:/root/.cache/llama.cpp
    command: >
      --hf-repo unsloth/Qwen3.5-27B-GGUF:Q4_K_S
      --alias coding-agent
      --host 0.0.0.0
      --port 8000
      -ngl 99
      -c 262144
      -np 1
      --jinja
      --cache-type-k q4_0
      --cache-type-v q4_0
      --flash-attn on
      --temp 0.6
      --top-p 0.95
      --min-p 0.0
      --top-k 20
      --presence-penalty 0.0
      --repeat-penalty 1.0
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              device_ids: ['0']
              capabilities: [gpu]
    restart: unless-stopped

  vllm-nvidia-nemotron-3-super:
    image: vllm/vllm-openai:nightly
    command: >
      --model nvidia/NVIDIA-Nemotron-3-Super-120B-A12B-NVFP4
      --port 8000
      --served-model-name model
      --tensor-parallel-size 1
      --enable-auto-tool-choice
      --enable-prefix-caching
      --language-model-only
      --tool-call-parser qwen3_coder
      --reasoning-parser qwen3
      --kv-cache-dtype fp8
      --gpu-memory-utilization 0.9
      --async-scheduling
      --trust-remote-code
      --attention-backend TRITON_ATTN
      --enable-chunked-prefill
      --max-num-seqs 512
      --max-model-len 1000000
      --reasoning-parser-plugin /config/plugins/reasoning/super_v3_reasoning_parser.py
      --reasoning-parser super_v3
    ports:
      - "8000:8000"
    volumes:
      - $HOME/.cache/huggingface:/root/.cache/huggingface
      - $HOME/github/ai-playground/tools/llm/vllm/source/config:/config
    runtime: nvidia
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              capabilities: [gpu]
              device_ids: ["1"]
    environment:
      - VLLM_ALLOW_LONG_MAX_MODEL_LEN=1

