---

services:

  ## llama.cpp ##

  # Qwen3.5 27b
  # Size: 27B
  # HF:
  #  - https://huggingface.co/unsloth/Qwen3.5-27B-GGUF
  #    - Q4_K_M
  #    - UD-Q4_K_XL - 23.06Gi
  #    - UD-Q8_K_XL ( 2 x RTX 3090 )
  #  - https://huggingface.co/Sepolian/Huihui-Qwen3.5-27B-Claude-4.6-Opus-abliterated-Q4_K_M
  #  - https://huggingface.co/Jackrong/Qwen3.5-27B-Claude-4.6-Opus-Reasoning-Distilled-GGUF
  # GPU(s): 1 x RTX 3090
  llamacpp-qwen3.5-27b:
    # Image tag: https://github.com/ggml-org/llama.cpp/actions/workflows/docker.yml
    image: ghcr.io/ggml-org/llama.cpp:server-cuda12-b8532
    runtime: nvidia
    environment:
      - NVIDIA_DRIVER_CAPABILITIES=compute,utility
      - LLAMA_CACHE=/root/.cache/llama.cpp
    ports:
      - "8002:8000"
    volumes:
      - ~/.cache/huggingface/hub:/root/.cache/huggingface/hub:rw
    command: >
      --hf-repo unsloth/Qwen3.5-27B-GGUF:UD-Q4_K_XL
      --alias coding-agent
      --host 0.0.0.0
      --port 8000
      -ngl 99
      -c 262144
      -np 2
      --jinja
      --cache-type-k q4_0
      --cache-type-v q4_0
      --flash-attn on
      --temp 0.6
      --top-p 0.95
      --min-p 0.0
      --top-k 20
      --presence-penalty 0.0
      --repeat-penalty 1.0
      --chat-template-kwargs '{"enable_thinking": false}'
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              device_ids: ['0']
              capabilities: [gpu]
    restart: unless-stopped

  # Qwen3.5 35b
  # Size: 35B
  # HF:
  #  - https://huggingface.co/unsloth/Qwen3.5-35B-A3B-GGUF - UD-IQ4_XS ( 1 x RTX 3090 )
  # GPU(s): 1 x RTX 3090
  llamacpp-qwen3.5-35b:
    image: ghcr.io/ggml-org/llama.cpp:server-cuda12-b8532
    runtime: nvidia
    environment:
      - NVIDIA_DRIVER_CAPABILITIES=compute,utility
      - LLAMA_CACHE=/root/.cache/llama.cpp
    ports:
      - "8002:8000"
    volumes:
      - ~/.cache/huggingface/hub:/root/.cache/huggingface/hub:rw
    command: >
      --hf-repo unsloth/Qwen3.5-35B-A3B-GGUF:UD-IQ4_XS
      --alias coding-agent
      --host 0.0.0.0
      --port 8000
      -ngl 99
      -c 131072
      --batch-size 4096
      --ubatch-size 2048
      --jinja
      --flash-attn on
      --temp 0.7
      --top-p 0.95
      --min-p 0.0
      --top-k 20
      --presence-penalty 0.0
      --repeat-penalty 1.0
      --reasoning-format auto
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              device_ids: ['1']
              capabilities: [gpu]
    restart: unless-stopped

  # Minimax M2.5
  # Size: 229B - 10B active
  # HF: https://huggingface.co/unsloth/MiniMax-M2.5-GGUF
  # GPU(s): 2 x RTX 6000 Pro
  llamacpp-minimax:
    image: ghcr.io/ggml-org/llama.cpp:server-cuda12-b8077
    runtime: nvidia
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=compute,utility
    ports:
      - "8002:8000"
    volumes:
      - ~/.cache/huggingface/hub:/root/.cache/huggingface/hub:rw
    command: >
      --host 0.0.0.0
      --port 8000
      --hf-repo unsloth/MiniMax-M2.5-GGUF:Q4_K_M
      --alias coding-agent
      --n-predict 196608
      --ctx-size 196608
      --batch-size 2048
      --parallel 1
      --cont-batching
      --cache-type-k q8_0
      --cache-type-v q8_0
      --flash-attn on
      --repeat-penalty 1.05
      --temp 1.0
      --top-k 40
      --min-p 0.05
      --top-p 0.95
      --jinja
      --fit on
      --reasoning-format auto
      --no-mmap
      --mlock
      --numa isolate
      --gpu-layers 999
      --metrics
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              device_ids: ['0','1']
              capabilities: [gpu]
    restart: unless-stopped

  ## VLLM ##

  vllm-open-webui-nvidia-nemotron-3-super:
    image: ghcr.io/open-webui/open-webui:latest
    ports:
      - 3001:8080
    environment:
      - OPENAI_API_BASE_URL=http://vllm-nvidia-nemotron-3-super:8000/v1
    restart: unless-stopped

  # Nemotron 3 Super
  # Size: 120B - 12B active
  # HF: https://huggingface.co/nvidia/NVIDIA-Nemotron-3-Super-120B-A12B-NVFP4
  # GPU(s): 1 x RTX 6000 Pro
  vllm-nvidia-nemotron-3-super:
    image: vllm/vllm-openai:nightly
    command: >
      nvidia/NVIDIA-Nemotron-3-Super-120B-A12B-NVFP4
      --port 8000
      --served-model-name model
      --tensor-parallel-size 1
      --enable-auto-tool-choice
      --enable-prefix-caching
      --language-model-only
      --tool-call-parser qwen3_coder
      --reasoning-parser qwen3
      --kv-cache-dtype fp8
      --gpu-memory-utilization 0.9
      --async-scheduling
      --trust-remote-code
      --attention-backend TRITON_ATTN
      --enable-chunked-prefill
      --max-num-seqs 8
      --max-num-batched-tokens 4096
      --max-model-len 500000
      --reasoning-parser-plugin /config/plugins/reasoning/super_v3_reasoning_parser.py
      --reasoning-parser super_v3
    ports:
      - "8000:8000"
    volumes:
      - $HOME/.cache/huggingface:/root/.cache/huggingface
      - $HOME/github/ai-playground/tools/llm/vllm/source/config:/config
    runtime: nvidia
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              capabilities: [gpu]
              device_ids: ["1"]
    environment:
      - VLLM_ALLOW_LONG_MAX_MODEL_LEN=1
    restart: unless-stopped

  # Mini 
  # Size: 27B
  # HF: https://huggingface.co/cyankiwi/Qwen3.5-27B-AWQ-4bit
  # GPU(s): 1 x RTX 3090 
  vllm-qwen3.5-27b:
    image: vllm/vllm-openai:v0.18.0-cu130
    pull_policy: always
    command: >
      cyankiwi/Qwen3.5-27B-AWQ-4bit
      --port 8000
      --served-model-name model
      --max-model-len 262144 
      --language-model-only
      --enable-auto-tool-choice
      --tool-call-parser qwen3_coder
      --reasoning-parser qwen3
      --kv-cache-dtype fp8
      --gpu-memory-utilization 0.96
      --max-num-seqs 1
      --max-num-batched-tokens 512
    ports:
      - "8000:8000"
    volumes:
      - $HOME/.cache/huggingface:/root/.cache/huggingface
      - $HOME/github/ai-playground/tools/llm/vllm/source/config:/config
    runtime: nvidia
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              capabilities: [gpu]
              device_ids: ["0"]
    environment: []
    restart: unless-stopped

  # Minimax M2.5
  # Size: 229B - 10B active
  # HF: https://huggingface.co/cyankiwi/MiniMax-M2.5-AWQ-4bit/blob/main/docs/vllm_deploy_guide.md
  # GPU(s): 2 x RTX 6000 Pro
  vllm-minimax-m2.5:
    image: vllm/vllm-openai:v0.18.0-cu130
    pull_policy: always
    command: >
      cyankiwi/MiniMax-M2.5-AWQ-4bit
      --port 8000
      --served-model-name model
      --max-model-len 262144
      --tensor-parallel-size 2
      --enable-expert-parallel
      --enable-auto-tool-choice --tool-call-parser minimax_m2
      --reasoning-parser minimax_m2_append_think
      --compilation-config "{\"cudagraph_mode\": \"PIECEWISE\"}"
    ports:
      - "8000:8000"
    volumes:
      - $HOME/.cache/huggingface:/root/.cache/huggingface
      - $HOME/github/ai-playground/tools/llm/vllm/source/config:/config
    runtime: nvidia
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              capabilities: [gpu]
              device_ids: ["0","1"]
    environment:
      - SAFETENSORS_FAST_GPU=1
    restart: unless-stopped

  # ComfyUI GPU
  # Setup:
  # - docker compose exec comfy-gpu git clone https://github.com/Comfy-Org/ComfyUI-Manager ComfyUI/custom_nodes/ComfyUI-Manager
  # Nodes:
  # - https://github.com/Comfy-Org/ComfyUI-Manager
  # - https://github.com/rgthree/rgthree-comfy
  # - https://github.com/Kosinkadink/ComfyUI-VideoHelperSuite
  # - https://github.com/Lightricks/ComfyUI-LTXVideo
  # - https://github.com/numz/ComfyUI-SeedVR2_VideoUpscaler
  # - https://github.com/1038lab/ComfyUI-QwenVL
  # - https://github.com/Fannovel16/comfyui_controlnet_aux
  # - https://github.com/PGCRT/CRT-Nodes
  # - https://github.com/dreamfast/ComfyUI-LTX2-MultiGPU
  # - https://github.com/BennyDaBall930/ComfyUI-Z-Engineer
  # - https://github.com/jtydhr88/ComfyUI-qwenmultiangle
  # - https://github.com/ltdrdata/ComfyUI-Impact-Pack
  # - https://github.com/yolain/ComfyUI-Easy-Use
  # - https://github.com/kijai/ComfyUI-KJNodes
  # - https://github.com/Fannovel16/ComfyUI-Frame-Interpolation
  # - https://github.com/PozzettiAndrea/ComfyUI-TRELLIS2
  # - https://github.com/Lightricks/ComfyUI-LTXVideo
  # - https://github.com/Jasonzzt/ComfyUI-CacheDiT
  comfy-gpu:
    image: yanwk/comfyui-boot:cu130-slim-20260306
    ports:
      - "8188:8188"
    security_opt:
      - "label=type:nvidia_container_t"
    volumes:
      - /data/models/comfy/models:/root/ComfyUI/models
      - /data/models/comfy/workflows:/root/ComfyUI/user/default/workflows
      - /data/models/comfy/custom_nodes:/root/ComfyUI/custom_nodes
    environment:
      CLI_ARGS: "--disable-xformers"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              device_ids: ['0']
              capabilities: [gpu]
    restart: unless-stopped 

