---

services:

  comfyui-llm:
    image: ghcr.io/ggml-org/llama.cpp:server-cuda12
    pull_policy: always
    runtime: nvidia
    environment:
      - NVIDIA_DRIVER_CAPABILITIES=compute,utility
      - LLAMA_CACHE=/root/.cache/llama.cpp
    volumes:
      - ~/.cache/huggingface/hub:/root/.cache/huggingface/hub:rw
    command: >
      --hf-repo unsloth/Qwen3.5-35B-A3B-GGUF:UD-IQ4_XS
      --hf-repo HauhauCS/Qwen3.5-9B-Uncensored-HauhauCS-Aggressive:Q4_K_M
      --alias coding-agent
      -ngl 99
      -c 16000 
      --jinja
      --flash-attn on
      --temp 0.7
      --top-p 0.95
      --min-p 0.0
      --top-k 20
      --presence-penalty 0.0
      --repeat-penalty 1.0
      --reasoning-format auto
      --chat-template-kwargs '{"enable_thinking": false}'
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              device_ids: ['0']
              capabilities: [gpu]
    restart: unless-stopped

  # ComfyUI GPU
  # Setup:
  # - docker compose exec comfy-gpu git clone https://github.com/Comfy-Org/ComfyUI-Manager ComfyUI/custom_nodes/ComfyUI-Manager
  # Nodes:
  # - https://github.com/Comfy-Org/ComfyUI-Manager
  # - https://github.com/rgthree/rgthree-comfy
  # - https://github.com/Kosinkadink/ComfyUI-VideoHelperSuite
  # - https://github.com/Lightricks/ComfyUI-LTXVideo
  # - https://github.com/numz/ComfyUI-SeedVR2_VideoUpscaler
  # - https://github.com/1038lab/ComfyUI-QwenVL
  # - https://github.com/Fannovel16/comfyui_controlnet_aux
  # - https://github.com/PGCRT/CRT-Nodes
  #   - Resolution ( CRT )
  # - https://github.com/dreamfast/ComfyUI-LTX2-MultiGPU
  # - https://github.com/BennyDaBall930/ComfyUI-Z-Engineer
  # - https://github.com/jtydhr88/ComfyUI-qwenmultiangle
  # - https://github.com/ltdrdata/ComfyUI-Impact-Pack
  # - https://github.com/yolain/ComfyUI-Easy-Use
  # - https://github.com/kijai/ComfyUI-KJNodes
  #   - GGUFLoaderKJ
  # - https://github.com/kijai/ComfyUI-MemoryVisualization
  # - https://github.com/Fannovel16/ComfyUI-Frame-Interpolation
  # - https://github.com/PozzettiAndrea/ComfyUI-TRELLIS2
  # - https://github.com/Lightricks/ComfyUI-LTXVideo
  # - https://github.com/Jasonzzt/ComfyUI-CacheDiT
  comfyui:
    image: yanwk/comfyui-boot:cu130-slim-v2-20260416
    ports:
      - "8188:8188"
    security_opt:
      - "label=type:nvidia_container_t"
    volumes:
      - /data/models/comfy/models:/root/ComfyUI/models
      - /data/models/comfy/workflows:/root/ComfyUI/user/default/workflows
      - /data/models/comfy/custom_nodes:/root/ComfyUI/custom_nodes
    environment:
      CLI_ARGS: "--disable-xformers"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              device_ids: ['0']
              capabilities: [gpu]
    restart: unless-stopped 

